<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="payment">
	<h3><?php echo sprintf(__('Invoice %s'), $this->escape($invoice['id'])); ?></h3>
	<div class="well">
		<p><strong><?php _e('Status'); ?></strong> : <?php if ($invoice['status'] == 1) { ?>
		<span class="label label-success"><?php _e('Paid'); ?><span>
		<?php } elseif ($invoice['status'] == 2) { ?>
		<span class="label label-warning"><?php _e('Unpaid'); ?><span>
		<?php } else { ?>
		<span class="label label-danger"><?php _e('Canceled'); ?><span>
		<?php } ?>
		<p><strong><?php _e('Module'); ?></strong> : <span><?php echo $this->escape($invoice['module']); ?> / <?php echo $this->escape($invoice['part']); ?></span></p>
		<p><strong><?php _e('Order'); ?></strong> : <span><?php echo $this->escape($invoice['item']); ?> </span></p>
		<p><strong><?php _e('Gateway'); ?></strong> : <span><?php echo $this->escape($invoice['adapter']); ?> </span></p>
		<p><strong><?php _e('Amount'); ?></strong> : <span><?php echo $this->escape($invoice['amount_view']); ?> </span></p>
		<p><strong><?php _e('Create'); ?></strong> : <span><?php echo $this->escape($invoice['time_create_view']); ?> </span></p>
	</div>
	<div class="clearfix">
		<?php foreach ($invoice['description'] as $description) { ?>
		<div class="well">
			<?php foreach ($description as $key => $value) { ?>
			<p><strong><?php echo $key; ?></strong> : <span><?php echo $value; ?></span></p>
			<?php } ?>
        </div>
		<?php } ?>
	</div>
	<div class="clearfix">
		<?php foreach ($invoice['log'] as $log) { ?>
		<div class="well">
			<p><strong><?php _e('Id'); ?></strong> : <?php echo $this->escape($log['id']); ?></p>
			<p><strong><?php _e('Invoice'); ?></strong> : <?php echo $this->escape($log['invoice']); ?></p>
			<p><strong><?php _e('Gateway'); ?></strong> : <?php echo $this->escape($log['gateway']); ?></p>
			<p><strong><?php _e('Create'); ?></strong> : <?php echo $this->escape($log['time_create_view']); ?></p>
			<p><strong><?php _e('User'); ?></strong> : <?php echo $this->escape($log['uid']); ?></p>
			<p><strong><?php _e('Amount'); ?></strong> : <?php echo $this->escape($log['amount_view']); ?></p>
			<p><strong><?php _e('Authority'); ?></strong> : <?php echo $this->escape($log['authority']); ?></p>
			<p><strong><?php _e('Status'); ?></strong> : <?php echo $this->escape($log['status']); ?></p>
			<p><strong><?php _e('Ip'); ?></strong> : <?php echo $this->escape($log['ip']); ?></p>
			<pre><?php print_r($log['value']); ?></pre>
        </div>
		<?php } ?>
	</div>
</div>