<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="payment">
	<h3><?php _e('List of Invoices'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Invoice'); ?></th>
			<th><?php _e('Adapter'); ?></th>
			<th><?php _e('Amount'); ?></th>
			<th><?php _e('User'); ?></th>
			<th><?php _e('Time Create'); ?></th>
			<th><?php _e('Ip'); ?></th>
		</tr>
		<?php foreach($list as $log) { ?>
		<?php
		if($log['status'] == 1) {
			$labelIdClass = 'label-success';	
		} elseif($log['status'] == 2) {
			$labelIdClass = 'label-warning';	
		} elseif($log['status'] == 3) {
			$labelIdClass = 'label-danger';	
		}
		?>
		<tr>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($log['id']); ?></span></td>
			<td><?php echo $this->escape($log['invoice']); ?></td>
			<td><?php echo $this->escape($log['gateway']); ?></td>
			<td><?php echo $this->escape($log['amount']); ?></td>
			<td><?php echo $this->escape($log['user']['identity']); ?></td>
			<td><?php echo $this->escape($log['time_create_view']); ?></td>
			<td><?php echo $this->escape($log['ip']); ?></td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
	<p>
		<span class="label label-success"><?php _e('Paid'); ?></span>
		<span class="label label-warning"><?php _e('Unpaid'); ?></span>
		<span class="label label-danger"><?php _e('Canceled'); ?></span>
	</p>
</div>