<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="payment">
	<h3><?php echo sprintf(__('Invoice %s'), _number($this->escape($invoice['id']))); ?></h3>
	<div class="well">
		<div class="clearfix">
			<div class="col-md-8">
				<p><strong><?php _e('Status'); ?></strong> : <?php if ($invoice['status'] == 1) { ?>
					<span class="label label-success"><?php _e('Paid'); ?><span>
				<?php } elseif ($invoice['status'] == 2) { ?>
					<span class="label label-warning"><?php _e('Unpaid'); ?><span>
				<?php } else { ?>
					<span class="label label-danger"><?php _e('Canceled'); ?><span>
				<?php } ?>
				<!-- <p><strong><?php _e('Module'); ?></strong> : <span><?php echo $this->escape($invoice['module']); ?> / <?php echo $this->escape($invoice['part']); ?></span></p> -->
				<p><strong><?php _e('Order'); ?></strong> : <span><?php echo $this->escape($invoice['item_view']); ?> </span></p>
				<p><strong><?php _e('Gateway'); ?></strong> : <span><?php echo $this->escape($invoice['adapter']); ?> </span></p>
				<p><strong><?php _e('Amount'); ?></strong> : <span><?php echo $this->escape($invoice['amount_view']); ?> </span></p>
				<p><strong><?php _e('Create'); ?></strong> : <span><?php echo $this->escape($invoice['time_create_view']); ?> </span></p>
			</div>
			<div class="col-md-4"></div>
		</div>
	</div>	
	<div class="clearfix">
		<?php foreach ($invoice['description'] as $description) { ?>
		<div class="well">
			<?php foreach ($description as $key => $value) { ?>
			<p><strong><?php echo $key; ?></strong> : <span><?php echo $value; ?></span></p>
			<?php } ?>
    	</div>
		<?php } ?>
	</div>
	<div class="clearfix"><a class="btn btn-primary" title="<?php _e('Pay'); ?>" href="<?php echo $this->escape($invoice['pay']); ?>"><?php _e('Pay'); ?></a></div>
</div>