CREATE TABLE `{order}` (
    `id` int(10) unsigned NOT NULL auto_increment,
    `uid` int(10) unsigned NOT NULL default '0',
    `code` varchar(16) NOT NULL default '',
    `ip` char(15) NOT NULL default '',
    `packing` tinyint(1) unsigned NOT NULL default '0',
    # Customer information
    `first_name` varchar(255) NOT NULL default '',
    `last_name` varchar(255) NOT NULL default '',
    `email` varchar(64) NOT NULL default '',
    `phone` varchar(16) NOT NULL default '',
    `mobile` varchar(16) NOT NULL default '',
    `company` varchar(255) NOT NULL default '',
    `address` text,
    `country` varchar(64) NOT NULL default '',
    `state` varchar(64) NOT NULL default '',
    `city` varchar(64) NOT NULL default '',
    `zip_code` varchar(16) NOT NULL default '',
    `company` varchar(255) NOT NULL default '',
    `company_id` varchar(255) NOT NULL default '',
    `company_vat` varchar(255) NOT NULL default '',
    # Notes
    `user_note` text,
    `admin_note` text,
    # Needed times
    `time_create` int(10) unsigned NOT NULL default '0',
    `time_payment` int(10) unsigned NOT NULL default '0',
    `time_delivery` int(10) unsigned NOT NULL default '0',
    `time_finish` int(10) unsigned NOT NULL default '0',
    `time_start` int(10) unsigned NOT NULL default '0',
    `time_end` int(10) unsigned NOT NULL default '0',
    # Needed status
    `status_order` tinyint(1) unsigned NOT NULL default '0',
    `status_payment` tinyint(1) unsigned NOT NULL default '0',
    `status_delivery` tinyint(1) unsigned NOT NULL default '0',
    # Needed prices
    `product_price` decimal(16,2) NOT NULL default '0.00',
    `discount_price` decimal(16,2) NOT NULL default '0.00',
    `shipping_price` decimal(16,2) NOT NULL default '0.00',
    `packing_price` decimal(16,2) NOT NULL default '0.00',
    `vat_price` decimal(16,2) NOT NULL default '0.00',
    `total_price` decimal(16,2) NOT NULL default '0.00',
    `paid_price` decimal(16,2) NOT NULL default '0.00',
    # Payment information
    `payment_method` enum('online','offline') NOT NULL default 'online',
    `payment_adapter` varchar(64) NOT NULL default '',
    # promos as gift
    `promo_type` varchar(64) NOT NULL default '',
    `promo_value` varchar(64) NOT NULL default '',
    #`delivery` int(10) unsigned NOT NULL default '0',
    #`location` int(10) unsigned NOT NULL default '0',
    #`item` int(10) unsigned NOT NULL default '0',
    #`package` int(10) unsigned NOT NULL default '0',
    PRIMARY KEY (`id`),
    KEY `uid` (`uid`),
);